export let products = [
  {
    id: 1,
    name: "iPhone 16",
    category: "Electronics",
    price: 85000,
    rating: 4.8,
  },
  {
    id: 2,
    name: "Samsung Galaxy S25",
    category: "Electronics",
    price: 72000,
    rating: 4.7,
  },
  {
    id: 3,
    name: "Nike Running Shoes",
    category: "Fashion",
    price: 6500,
    rating: 4.5,
  },
  {
    id: 4,
    name: "Levi's Jeans",
    category: "Fashion",
    price: 3200,
    rating: 4.3,
  },
  {
    id: 5,
    name: "Wooden Study Table",
    category: "Furniture",
    price: 12000,
    rating: 4.2,
  },
  {
    id: 6,
    name: "Office Chair",
    category: "Furniture",
    price: 7800,
    rating: 4.6,
  },
  {
    id: 7,
    name: "The Alchemist",
    category: "Books",
    price: 499,
    rating: 4.9,
  },
  {
    id: 8,
    name: "Atomic Habits",
    category: "Books",
    price: 699,
    rating: 4.8,
  },
  {
    id: 9,
    name: "Football",
    category: "Sports",
    price: 1200,
    rating: 4.4,
  },
  {
    id: 10,
    name: "Cricket Bat",
    category: "Sports",
    price: 3500,
    rating: 4.7,
  },
];